### ISSUE TITLE
Supported public keys

### ISSUE THREAD

**Issue by tobiasb** [firebase/php-jwt#336] opened 2021-05-26 16:54 UTC
I'm trying to decode a JWT signed by a ES256 key via `$decoded = JWT::decode($jwt, $key, array('ES256'));`. This is the public key:

```
{
    "keys": [
        {
            "crv": "P-256",
            "x": "Bt3X2qfuC4A7VfqzdZVnmJm-_0iisYJK9TKdOsyqxrA",
            "y": "3BdE6-X4VfC8Iyw6NQiu9HXTHNs4QX7kXwWbTQztDFw",
            "kty": "EC"
        }
    ]
}
```

I'm getting the following error: `Uncaught UnexpectedValueException: No supported algorithms found in JWK Set in /var/www/vhosts/avaaz.org/releases/repo/vendor/firebase/php-jwt/src/JWK.php:55` and looking at that file it seems that indeed only `RSA` is supported right now. Is that the case or am I misunderstanding something?

**Comment by bshaffer** [comment] 2021-05-27 22:06
Unfortunately that is currently the case, yes. JWKs only support RSA. I'll experiment with adding it this week, however, as it seems like an obvious need.

**Comment by bshaffer** [comment] 2021-05-27 22:07
Closing as a duplicate of https://github.com/firebase/php-jwt/issues/337

**Closed by bshaffer** 2021-05-27 22:07 UTC
