### ISSUE TITLE
Using CachedKeySet causes an Exception thrown by openssl_verify()

### ISSUE THREAD

**Issue by Brunty** [firebase/php-jwt#429] opened 2022-05-17 08:47 UTC
`ErrorException: openssl_verify(): supplied key param cannot be coerced into a public key in /var/www/html/vendor/firebase/php-jwt/src/JWT.php:293`

I've tried with both a Redis cache and a Filesystem cache (provided by the [Symfony Cache Component](https://symfony.com/doc/current/components/cache.html)).

The first time the code is called and it doesn't have anything in the cache, it works fine. The second time it's called I get the above error.

**Comment by Brunty** [comment] 2022-05-18 10:45
I'm wondering if something about the way things are stored in a PSR-6 cache is causing this? Writing a basic "store the JWKs in cache and fetch on next request" type implementation myself yields the same error.

**Comment by BenjaminFavre** [comment] 2022-06-03 15:01
Starting with PHP 8, openssl_pkey_get_public() returns an instance of OpenSSLAsymmetricKey, which is not serializable by design.

I suggest to cache only the JWKS string, so there is no serialization issue and the cache is still very effective because it avoids unnecessary network calls to the JWKS URI.

**Comment by Brunty** [comment] 2022-06-03 19:59
Yeah.

The current process is Fetch -> Parse -> Cache

IMO it should be Fetch -> Cache -> Parse

**Comment by brandomeniconi** [comment] 2022-06-07 16:11
+1 here, even using phpfastcache:files as the example suggested.

**Comment by bshaffer** [comment] 2022-07-15 16:51
Thank you for finding and fixing this. This should now be fixed in [v6.3.0](https://github.com/firebase/php-jwt/releases/tag/v6.3.0)!

**Closed by bshaffer** 2022-07-15 16:51 UTC
