### ISSUE TITLE
OpenSSL Error openssl_verify()

### ISSUE THREAD

**Issue by vgavrilovikj** [firebase/php-jwt#289] opened 2020-03-29 18:09 UTC
When I am trying to validate the token I get, the error below:
"OpenSSL error: error:0909006C:PEM routines:get_name:no start line"

This is how I am decoding the JSON:
`$decoded = JWT::decode($jwt, $privateKey, array('RS256'));`

And this is the code where it throws an error:
```
 private static function verify($msg, $signature, $key, $alg)
    {
        if (empty(static::$supported_algs[$alg])) {
            throw new DomainException('Algorithm not supported');
        }

        list($function, $algorithm) = static::$supported_algs[$alg];
        switch ($function) {
            case 'openssl':
                $success = \openssl_verify($msg, $signature, $key, $algorithm);
                if ($success === 1) {
                    return true;
                } elseif ($success === 0) {
                    return false;
                }
                // returns 1 on success, 0 on failure, -1 on error.
                throw new DomainException(
                    'OpenSSL error: ' . \openssl_error_string()
                );
            case 'hash_hmac':
            default:
                $hash = \hash_hmac($algorithm, $msg, $key, true);
                if (\function_exists('hash_equals')) {
                    return \hash_equals($signature, $hash);
                }
                $len = \min(static::safeStrlen($signature), static::safeStrlen($hash));

                $status = 0;
                for ($i = 0; $i < $len; $i++) {
                    $status |= (\ord($signature[$i]) ^ \ord($hash[$i]));
                }
                $status |= (static::safeStrlen($signature) ^ static::safeStrlen($hash));

                return ($status === 0);
        }
    }
```

**Comment by davidkeefe24** [comment] 2020-07-30 22:30
I am getting this same error. Did you solve your issue @vgavrilovikj ?

**Comment by JasmanDev** [comment] 2020-08-16 07:17
@vgavrilovikj Same error for me. Did you solve it?

**Comment by KlimovOleg** [comment] 2020-08-28 00:50
When can you make a fix?

**Comment by thnardi** [comment] 2021-03-17 07:04
Same problem here. I noticed you are using $privateKey in the code you show here. Have you tried using your $pubkey? Here the error are the same, even me using the public key.

**Comment by vgavrilovikj** [comment] 2021-03-17 21:43
I didn't find a fix..... @thnardi

**Comment by lindelius** [comment] 2021-03-17 21:56
The issue is most likely that the key is badly formatted. A common error is that the newlines are just "\n" in plaintext, instead of actual newlines.

**Comment by thnardi** [comment] 2021-03-18 03:04
I found a solution to my problem... @lindelius is right... it is about the badly formatted key. In my case, i've a auth api with a endpoint that returns the public key, to other servers decode token.. The API is build with slim framework and was returning in a PSR response with this line of code: `return $response->withJson($data['public']);`

And don't dig too mutch, just change it and force a `echo` $data['public'];` to force this pure stream of data in endpoint and it works.

**Comment by kimthangatm** [comment] 2021-04-10 16:21
Same error in Php 7.3 in MacOS Big Sur. I switch to Php 7.2, it work.

**Comment by atsokha** [comment] 2022-03-16 08:58
The problem is probably in the keys themselves.

First, use the public key for decoding.

Second, to be sure that your keys are generated correctly, validate them for example at - https://www.sslchecker.com/certdecoder

Third - try to generate keys in an online generator, for example here - https://travistidwell.com/jsencrypt/demo/

**Comment by bshaffer** [comment] 2023-06-28 17:32
Yes, this problem is in the keys themselves, and does not have to do with this library. I am closing this issue because there's nothing actionable in this repo.

Thanks for the thorough response @atsokha

**Closed by bshaffer** 2023-06-28 17:32 UTC
