### ISSUE TITLE
How about some documentation?

### ISSUE THREAD

**Issue by marcospgp** [firebase/php-jwt#58] opened 2015-07-01 15:53 UTC
I feel this library could use some documentation, especially some mention that if the token verification fails, an exception will be thrown. Also an example of code where a try catch block is used to decode a token would help.

 Thanks!

**Comment by toddmcbrearty** [comment] 2015-08-11 17:15
+1

**Comment by peterholcomb** [comment] 2015-08-11 17:24
:+1:   Great library by the way, very helpful in my latest project

**Comment by Mrkisha** [comment] 2015-09-15 19:47
+1

**Comment by dperjar** [comment] 2015-09-15 21:04
I generally agree but if anyone really does need some examples etc the tests aren't a bad place to start: https://github.com/firebase/php-jwt/blob/master/tests/JWTTest.php

**Comment by rutwick** [comment] 2015-10-13 13:34
+1

**Comment by spacebiscuit** [comment] 2015-11-10 16:57
+5

**Comment by xerardoo** [comment] 2016-03-04 17:39
+10

**Comment by sonicwong** [comment] 2016-04-21 08:28
+1

**Comment by fireproofsocks** [comment] 2016-09-27 20:59
+1 https://medium.com/@craftsmancoding/wtfm-dbbec02eb172#.nqpu6uivi

**Comment by ajupazhamayil** [comment] 2023-05-14 20:04
I see exception handling example is added to the readme itself and the issue is really old. Closing this issue. Thank you for the discussion.

**Closed by ajupazhamayil** 2023-05-14 20:04 UTC
